### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by couzic** [couzic/adaptac#2]
Un des besoins critiques de l'application est de pouvoir envoyer des notifications aux adhérents. Par exemple, si à la dernière minute un cours est déplacé sur le stade pour cause de salle indisponible, une notification est envoyée à tous les élèves de ce cours. Plusieurs possibilités non-mutuellement exclusives:

- Polling
- Push server
- Mails
- SMS

Pour les SMS, le coût est compris entre 4 et 5 centimes le SMS.

**Comment by couzic** [comment]
Les notifications Push sont plus complexes et contraignantes à utiliser. Notamment, dans le cas d'une PWA (Progressive Web App), les notifications ne marcheront pas forcément sur tous les appareils.

L'envoi de mails + SMS a l'avantage est dans la simplicité d'implémentation, et la garantie maximale de réception du message. Par contre il y a un coût pour les SMS.

**Comment by foksan** [comment]
On pourrait le configurer lors de la création du profile utilisateur en mettant par défaut du push + mail à tout le monde et pour ceux qui le souhaitent ou qui n'ont pas de smartphone la notification sms.
Cela évitera d'envoyer systématiquement un sms et ce fera des économies.

**Comment by foksan** [comment]
Voir si on peut utiliser un package qui permet d'envoyer des sms depuis le téléphone de l'utilisateur (avec rôle admin):
https://ionicframework.com/docs/native/sms/

Je pense qu'on a en majorité des forfaits avec sms illimités.

**Comment by couzic** [comment]
On part sur cette dernière option plugin SMS + mails
