### ISSUE TITLE
Application Web ou Mobile ?

### ISSUE THREAD

**Issue by couzic** [couzic/adaptac#3]
Plusieurs possibilités pour l'application:

- Web Responsive (web + mobile)
- Web Progressive (web + mobile)
- Hybride (mobile)
- Native (mobile)

On envisage une utilisation multi-plateforme, donc la solution PWA (Progressive Web App) peut éviter de développer deux applications différentes.
Alternativement, des solutions comme NativeScript permettent de développer un socle commun à deux applications web et mobile, et à ne développer deux fois que les composants graphiques, la gestion des notifications, geoloc, ce genre de choses. Au minimum il y aura quand même 40% de l'appli à développer deux fois.

Le choix du type de solution choisie dépend des besoins en notifications, point traité dans le ticket #2
Si on considère que la solution mails + SMS répond aux besoins, dans ce cas l'option PWA sera sans doute la plus pertinente.

**Comment by foksan** [comment]
PWA rocks d'après ce que j'ai lu on a plus de possibilités.

**Comment by couzic** [comment]
On part sur du Hybride pour pouvoir utiliser le plugin Cordova permettant d'envoyer programmatiquement des SMS depuis le portable de l'utilisateur
